name: Notify Changed Files on Merge

on:
  push:
    branches:
      - main
      - development

jobs:
  notify_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get List of Changed Files
      id: changed_files
      run: |
        # Get a list of files changed between the current and previous commit
        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "Changed files: $FILES"
        
        # Save the files to be used in later steps
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Send Files to Webhook
      run: |
        # Prepare the file names as a JSON array
        JSON_PAYLOAD=$(echo $FILES | sed 's/ /","/g' | sed 's/^/["/' | sed 's/$/"]/')
        
        # Send the list of changed files to the webhook URL
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"files\": $JSON_PAYLOAD}" \
          "https://hook.app.workfrontfusion.com/5kr0cnn1g1ry3aemmz64b6h95nz4pamd"
